# -*- coding: utf-8 -*-
"""A1 ISAAC EZEQUIEL TDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i4Jd6XHAisHw9G-FL_uaIEV8u3FBzl_q
"""

# Exercício 1 - Estruturas Condicionais
idade = int(input("Digite sua idade: "))

if idade < 0:
    print("Idade inválida.")
elif idade < 12:
    print("Entrada permitida apenas acompanhado dos pais.")
elif idade < 18:
    print("Entrada permitida somente com autorização.")
else:

# Exercício 2 - Estruturas de Repetição

print("Números pares de 1 a 100 usando for:")
for i in range(1, 101):
    if i % 2 == 0:
        print(i, end=" ")

print("\n\nNúmeros pares de 1 a 100 usando while:")
i = 1
while i <= 100:
    if i % 2 == 0:
        print(i, end=" ")
    i += 1

# Exercício 3 - Listas
alunos = []

qtd = int(input("Quantos alunos deseja cadastrar? "))

for i in range(qtd):
    nome = input(f"Digite o nome do aluno {i+1}: ")
    alunos.append(nome)

print("\nLista de alunos cadastrados:")
for nome in alunos:
    print("-", nome)

# Exercício 4 - Dicionários
produtos = {}

qtd = int(input("Quantos produtos deseja cadastrar? "))

for i in range(qtd):
    nome = input(f"Digite o nome do produto {i+1}: ")
    preco = float(input("Digite o preço: "))
    produtos[nome] = preco

print("\nProdutos cadastrados:")
for nome, preco in produtos.items():
    print(f"{nome}: R$ {preco:.2f}")